"""add content field to articles

Revision ID: c8a0aa5e3ace
Revises: b7c7c9ee2eea
Create Date: 2026-04-28 05:06:37.461349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a0aa5e3ace'
down_revision: Union[str, None] = 'b7c7c9ee2eea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'content')
    # ### end Alembic commands ###
